### ISSUE TITLE
Windows Defender alert on Trojan:Win32/Fuery.C!cl on version 0.1.4

### ISSUE THREAD

**Issue by DavidConstantine88** [manojVivek/responsively-app#106] opened 2020-05-23 16:40 UTC
![image](https://user-images.githubusercontent.com/30372827/82735810-2d75b780-9d2d-11ea-9536-fba456be4c71.png)

**Comment by manojVivek** [comment] 2020-05-23 17:18
Duplicate of #96.

**Closed by manojVivek** 2020-05-23 17:18 UTC
