### ISSUE TITLE
Store zoom value between sessions

### ISSUE THREAD

**Issue by naher94** [manojVivek/responsively-app#345] opened 2020-07-24 19:58 UTC
would be awesome to store the zoom value between session. current behavior seems to reset to 60% zoom

**Comment by manojVivek** [comment] 2020-07-25 04:56
Duplicate of #320 

@naher94 This went live on v0.8.0. Can you please check if you are using the latest version of the app?

**Comment by naher94** [comment] 2020-07-25 14:21
Hi @manojVivek I do have version 0.8.0 but it doesn't seem to store the zoom setting cross sessions. I there a specific action that has to be taken to keep it sticky?
 
Version: 0.8.0
Electron: 8.4.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0

**Comment by manojVivek** [comment] 2020-07-25 15:33
@naher94 I'm attaching a screencast of how it works for me. Is it not working the same for way for you? 

![zoom-level-recording](https://user-images.githubusercontent.com/1283424/88460489-28162400-ceba-11ea-88aa-823e17e235ee.gif)

**Comment by naher94** [comment] 2020-07-25 16:01
Same process exactly.. but seemed to have sorted its self out now... maybe a caching issue? Either way thanks for you help!

**Closed** 2020-07-26 16:56 UTC
Labels: more info needed
