### ISSUE TITLE
[Feature Suggestion] Mobile devices realistic behaviour 

### ISSUE THREAD

**Issue by marekmalik** [manojVivek/responsively-app#230] opened 2020-06-27 11:45 UTC
Hi,

as a UX designer I'm wiling to use Responsively App to web audits, where I check usability and web behaviour on mobile devices.
It would be great if mobile devices in Responsively App will interact more realistic.

What I mean "more realistic":

- no hover effects
- a round cursor resembling the dimensions of a human finger
- scroll by touch
- maybe someone will add more...

I believe that this feature help UX designers as well as Web Developers on a common path in identifying potential usability problems on web they build together.

Thank you in advance for your consideration.

Marek

**Comment by manojVivek** [comment] 2020-06-27 15:53
@marekmalik Thanks for raising this request. This is already being worked on as part of #31. You can watch out for it in future releases. 

Closing this as a duplicate of #31

**Closed by manojVivek** 2020-06-27 15:53 UTC
