### ISSUE TITLE
[BUG] Globally disables CTRL+R shortcut on ubuntu

### ISSUE THREAD

**Issue by elderapo** [manojVivek/responsively-app#93] opened 2020-05-22 00:25 UTC
When an instance of `responsively-app` is running it's no longer possible to use `ctrl+r` shortcut for other applications. Is it a bug or intended behavior?

**Comment by manojVivek** [comment] 2020-05-22 09:16
This is a duplicate of #83 and the fix went live on v0.1.4 yesterday.

**Closed by manojVivek** 2020-05-22 09:16 UTC
Labels: duplicate

**Comment by elderapo** [comment] 2020-05-22 15:54
@manojVivek Now `ctrl+r` doesn't refresh `responsively-app` if it isn't focused (at least not on `ubuntu 20.04`).

**Comment by manojVivek** [comment] 2020-05-22 16:15
@elderapo Sorry, that is the expected behavior right?

**Comment by elderapo** [comment] 2020-05-22 16:20
Ideally `ctrl+r` should trigger `responsively-app` reload and at the same time work just fine for other applications. In other words, it could be intercepted by `responsively-app` but also should be forwarded to the currently focused application.

**Comment by manojVivek** [comment] 2020-05-22 16:34
@elderapo I don't think that is the right behavior. The current one matches how browsers like Chrome and Firefox handle this.
