### ISSUE TITLE
popup-blocked

### ISSUE THREAD

**Issue by jalejandro0211** [manojVivek/responsively-app#267] opened 2020-07-04 02:53 UTC
how to enable popups?

**Comment by manojVivek** [comment] 2020-07-04 03:57
@jalejandro0211 Is this for the js popups like `alert` or `New tab` type?

**Comment by jalejandro0211** [comment] 2020-07-04 12:41
> @jalejandro0211 Is this for the js popups like `alert` or `New tab` type?

Hi @manojVivek js popups like newtab

**Comment by manojVivek** [comment] 2020-07-04 15:34
@jalejandro0211 We have another issue open for this issue. #248. Please watch for the updates there, closing this as a duplicate of #248.

**Closed by manojVivek** 2020-07-04 15:34 UTC
