### ISSUE TITLE
Adding a new device moves all devices from Inactive Devices column to Active Devices column, does not add new device

### ISSUE THREAD

**Issue by CalamityAdam** [manojVivek/responsively-app#130] opened 2020-05-28 12:41 UTC
### Description
When adding a new device, after filling out the device info and clicking "Add", all devices from the `Inactive Devices` column are immediately moved to `Active Devices` column. The new device is not actually created. Furthermore, when I drag-and-drop the devices _back_ to the `Inactive Devices` column, the device card disappears. The behavior from the home screen accurately reflects what devices are in the `Active Devices` column, but the `Inactive Devices` column remains empty until restarting the program.
### App Details
Responsively version 0.1.5
MacOS 10.15.4
### Steps to Reproduce
1. In sidebar, under `DEVICES`, click `CUSTOMIZE`
2. From `Manage Devices` screen, click `+ NEW DEVICE`
3. Add device information (seemingly any combination of information and options selected yield the same results)
4. Click `ADD` - this will move all device cards from `Inactive` to `Active` and new device is not created
5. Click and Drag any device card from `Active` column to `Inactive` column and they disappear.

**Comment by esprush** [comment] 2020-05-28 12:52
Duplicate of #125

**Comment by esprush** [comment] 2020-05-28 12:55
@CalamityAdam thanks for reporting. this fix will go live in v0.1.6

**Closed** 2020-05-28 13:04 UTC
Labels: duplicate
