### ISSUE TITLE
React-responsive media query not working on Responsively

### ISSUE THREAD

**Issue by gilesbain** [manojVivek/responsively-app#156] opened 2020-06-01 18:08 UTC
Hi there,

I have a site that is displaying different grid layouts dependent on the results of a react-responsive media query e.g 

`  const isOnDesktop = useMediaQuery({ query: "(min-device-width: 1025px)" }); `

In chrome, edge, firefox this works great however when I use responsively I only am able to see the desktop layout as this is always returning true. Seems like it could be a compatibility thing but worries me that this could be a larger package compatibility issue.

<img width="1677" alt="Screenshot 2020-06-01 at 19 03 05" src="https://user-images.githubusercontent.com/18421659/83439551-4b34d200-a43b-11ea-90f4-023d890394fe.png">

![Screenshot 2020-06-01 at 19 05 35](https://user-images.githubusercontent.com/18421659/83439588-5f78cf00-a43b-11ea-8f4c-f18feaee6f98.png)

**Comment by jjavierdguezas** [comment] 2020-06-01 19:54
maybe this is a duplicate of #121 or at least there are related

**Comment by manojVivek** [comment] 2020-06-02 10:07
@gilesbain The problem here is because you used `min-device-width` instead of `min-width`. Is there a specific reason why you are using `min-device-width`? 

Your app will work fine, universally, if you have used `min-width` as a media query. 

You can also check this answer, it is a general best practice to use `min-width` instead of `min-device-width` unless you have a special reason for it - https://stackoverflow.com/a/15276588/586836

**Comment by sprabowo** [comment] 2020-06-12 12:20
Just additional information about device width or device height. Deprecated media queries https://polypane.app/blog/the-complete-guide-to-css-media-queries/#deprecated-media-queries

**Comment by manojVivek** [comment] 2020-06-12 13:03
Closing as wont-fix as this is the intended behavior for the used media-query.

**Closed by manojVivek** 2020-06-12 13:03 UTC
