### ISSUE TITLE
All inactive devices become active after adding a new device

### ISSUE THREAD

**Issue by johndavemanuel** [manojVivek/responsively-app#159] opened 2020-06-03 10:03 UTC
I am using Win 10 Pro, after I add new device and after saving it, all the inactive devices become active, then when I drag the active devices to inactive devices, they just gone after couple of seconds.

I replicate the issue twice so I guess something is wrong

**Comment by manojVivek** [comment] 2020-06-03 10:47
@johndavemanuel Can you please check the version you are using? The fix for this went in last release v0.1.6. 

Duplicate of #125

**Comment by johndavemanuel** [comment] 2020-06-03 10:49
![image](https://user-images.githubusercontent.com/8970365/83628353-ec9e5e00-a5ca-11ea-84a6-0e55e60674a4.png)

**Comment by johndavemanuel** [comment] 2020-06-03 10:49
0.1.6

**Comment by manojVivek** [comment] 2020-06-04 08:45
@johndavemanuel I just verified in v0.1.6 that this is not the behavior. Can you please share with us the exact steps that can reproduce this?

**Comment by jjavierdguezas** [comment] 2020-06-04 09:47
I can't reproduce it either with
>Version: 0.1.6
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by johndavemanuel** [comment] 2020-06-04 12:19
@manojVivek @jjavierdguezas I will record my screen and share to you guys

**Comment by manojVivek** [comment] 2020-06-13 13:23
Closing due to inactivity.

**Closed by manojVivek** 2020-06-13 13:23 UTC
Labels: more info needed

**Comment by johndavemanuel** [comment] 2020-06-14 10:20
Weird. I cannot replicate it. But I am sure it happens twice.
