### ISSUE TITLE
Changing a web page hash causes the browser to reload the page.

### ISSUE THREAD

**Issue by TrueXakeP** [manojVivek/responsively-app#145] opened 2020-05-30 04:43 UTC
It seems that changing the web page hash causes the browser to reload the page. The problem is that the completely one-page web application that I am currently working on is not compatible with this. It is fully loaded when you open it and then relies on the hash change. So it reboots from scratch every time you navigate and loses its state.

**Comment by manojVivek** [comment] 2020-05-30 05:53
Duplicate of #100 

The fix will go in with v0.1.6 this weekend.

**Closed by manojVivek** 2020-05-30 05:53 UTC

**Comment by TrueXakeP** [comment] 2020-05-30 06:17
Oh, sorry for a duplicate.
