### ISSUE TITLE
 Add new device does not work

### ISSUE THREAD

**Issue by lorettalorrain** [manojVivek/responsively-app#129] opened 2020-05-28 12:36 UTC
When I want to add a new device, it is not added, plus it moves all inactive devices to the active devices column.
I'm working on macOs

**Comment by manojVivek** [comment] 2020-05-28 13:05
@lorettalorrain This already fixed and it will go live in next release. v0.1.6.

Duplicate of #125.

**Closed by manojVivek** 2020-05-28 13:05 UTC
