### ISSUE TITLE
Inspect element, click instead of select

### ISSUE THREAD

**Issue by geiras** [manojVivek/responsively-app#319] opened 2020-07-16 14:47 UTC
When I'm trying to use the Inspect element feature to find the styles of a specific element, I expect that element to be selected on the Elements tab. What's happening is that, if the element has an action, that action is running. 

Ex: I have a button, I want to inspect to check background color. If I change to Inspect element and then click on the button, the button will do its action.

Suggestion: Disable all actions when clicking with Inspect element mode on.

**Comment by manojVivek** [comment] 2020-07-16 15:56
@geiras Thanks for raising this. Yeah, we are aware of it. This doesn't happen for all elements but yeah for some elements the inspection click triggers the click action.

The solution is to integrate the chromium native elements inspector for this option. And it is being dealt in #202.

Duplicate of #202. Please watch there for updates.

**Closed by manojVivek** 2020-07-16 15:56 UTC

**Comment by geiras** [comment] 2020-07-16 16:03
I searched for a similar issue before opening this one and I couldn't find it. I suspected it was a deeper issue and a bit more complicated than what I said.

So far, it happened on all elements with a link/action.
Will keep an eye on #202 for updates.

Thanks.
